- CMakeLists.txt
- Cutelyst/Actions/REST/CMakeLists.txt
- Cutelyst/Actions/RenderView/CMakeLists.txt
- Cutelyst/Actions/RoleACL/CMakeLists.txt
make it easier for package maintainers to choose a different install location for cutelyst plugins
> Custom plugin install location

- Cutelyst/Plugins/Session/CMakeLists.txt
- Cutelyst/Plugins/Session/sessionstorememcached.cpp
- Cutelyst/Plugins/Session/sessionstorememcached.h
- Cutelyst/Plugins/Session/sessionstorememcached_p.h
> Memcache session store

- Cutelyst/Plugins/Utils/Sql/sql.cpp
- Cutelyst/Plugins/Utils/Sql/sql.h
OK, next try. Seems I had a bad build cache.
> querytoIndexedHash

- Cutelyst/application.cpp
- Cutelyst/application.h
- Cutelyst/engine.cpp
- Cutelyst/engine.h
- Cutelyst/request.h
- Cutelyst/response.cpp
- Cutelyst/response.h
- README.md
- tests/coverageobject.cpp
- uwsgiEngine/engineuwsgi.cpp
- uwsgiEngine/engineuwsgi.h
- wsgi/CMakeLists.txt
- wsgi/cwsgiengine.cpp
- wsgi/cwsgiengine.h
- wsgi/localserver.cpp
- wsgi/protocol.cpp
- wsgi/protocol.h
- wsgi/protocolfastcgi.cpp
- wsgi/protocolhttp.cpp
- wsgi/protocolwebsocket.cpp
- wsgi/protocolwebsocket.h
- wsgi/socket.cpp
- wsgi/socket.h
- wsgi/tcpserver.cpp
- wsgi/tcpsslserver.cpp
> Websockets

- Cutelyst/Plugins/Memcached/memcached.h
- Cutelyst/Plugins/MemcachedSessionStore/memcachedsessionstore.h
- Cutelyst/Plugins/Session/CMakeLists.txt
- Cutelyst/Plugins/Session/sessionstorememcached.cpp
- Cutelyst/Plugins/Session/sessionstorememcached.h
- README.md
- cmd/main.cpp
- dox/Mainpage.dox
* adds Memcached and CSRF protection to the plugin list in the README.md
* adds CSRFProtection to the plugin list on the API docs main page
* adds a note about limitations to the MemcachedSessionStore plugin API docs
> Documentation improvements

- Cutelyst/Plugins/Memcached/memcached.cpp
Sadly the last commit and PR 79 did not solve the issue completely.
Adding memcached servers connected via unix socket files through the
configuration string did not work as expected. So I decided to choose a
different approach by using libmemcached's memcached_server_add_*
functions to add servers and sockets. Beside socket connections now work
this has the other advantage to have return status codes for every
server that will be added.
> Memcached plugin: finally fix connection to unix socket files

- CMakeLists.txt
- Cutelyst/Plugins/CSRFProtection/CMakeLists.txt
- Cutelyst/Plugins/Memcached/CMakeLists.txt
- Cutelyst/Plugins/MemcachedSessionStore/CMakeLists.txt
- dox/CMakeLists.txt
- dox/cutelyst-wsgi.1.in
- dox/cutelyst.1.in
I added them into the dox directory, not sure if that is the place you like to have them. :) I filled them with information that was available from the command line help.
I also set a conditional to only install them on UNIX like systems, because I think that the majority of Windows users will not have groff installed.
> Add man pages for cutelyst and cutelyst-wsgi

- Cutelyst/Plugins/Utils/LangSelect/CMakeLists.txt
> LangSelect plugin: fix install of library

- Cutelyst/Plugins/View/Grantlee/grantleeview.cpp
- Cutelyst/Plugins/View/Grantlee/grantleeview.h
- Cutelyst/application.cpp
This does the same as Application::loadTranslationsFromDir() does, but
only for the GrantleeView templates.
>  GrantleeView: add convenience function to load translations from dir 

- wsgi/tcpsslserver.h
> Fixed support for No-SSL mode

- wsgi/protocolfastcgi.cpp
> fix fastcgi protocol in combination with a body QIODevice

- Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
- Cutelyst/response.cpp
> make csrf field and redirect message html5/xhtml compatible

- CMakeLists.txt
- cmake/modules/CPackConfig.cmake
Added support for cpack to generate packages (deb, rpm, etc).
> Add cpack support (deb, rpm, etc)

- Cutelyst/Plugins/Memcached/memcached.cpp
- Cutelyst/Plugins/Utils/Validator/validatoraccepted.cpp
- Cutelyst/Plugins/Utils/Validator/validatoralphadash.cpp
- Cutelyst/Plugins/Utils/Validator/validatoralphanum.cpp
- Cutelyst/Plugins/Utils/Validator/validatordatetime.cpp
- Cutelyst/Plugins/Utils/Validator/validatorinteger.cpp
- Cutelyst/Plugins/Utils/Validator/validatorpwquality.cpp
- Cutelyst/Plugins/Utils/Validator/validatortime.cpp
- Messages.sh
- i18n/cutelystcmd.de.ts
- i18n/cutelystcore.de.ts
- i18n/cutelystwsgi.de.ts
- i18n/cutelystwsgi.en.ts
- i18n/plugin_csrfprotection.de.ts
- i18n/plugin_memcached.de.ts
- i18n/plugin_memcached.en.ts
- i18n/plugin_utils_validator.de.ts
- i18n/plugin_utils_validator.en.ts
- i18n/plugin_view_grantlee.de.ts
Fix some translatable strings in the Validator plugin and add German translation files.
> Translation updates

- Cutelyst/controller.cpp
- tests/CMakeLists.txt
- tests/testcontroller.cpp
Fixes: https://github.com/cutelyst/cutelyst/issues/280
> controller: support controllers declared inside C++ namespaces

- Cutelyst/CMakeLists.txt
- Cutelyst/ComponentFactory
- Cutelyst/componentfactory.h
Fix wrong include of Context and add a Qt-style header for convenience, 2nd try.
> Fix public component factory header

- Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
- Cutelyst/Plugins/CSRFProtection/csrfprotection_p.h
- Cutelyst/Plugins/Memcached/memcached.cpp
- Cutelyst/Plugins/Memcached/memcached_p.h
- Cutelyst/Plugins/MemcachedSessionStore/memcachedsessionstore.cpp
- Cutelyst/Plugins/MemcachedSessionStore/memcachedsessionstore_p.h
- Cutelyst/Plugins/Utils/LangSelect/langselect.cpp
- Cutelyst/Plugins/Utils/LangSelect/langselect_p.h
- Cutelyst/Plugins/Utils/Validator/validatorcharnotallowed.h
- Cutelyst/Plugins/Utils/Validator/validatorregularexpression.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredifstash.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredunless.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredunlessstash.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredwithall.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredwithout.h
- Cutelyst/Plugins/Utils/Validator/validatorrequiredwithoutall.h
- Cutelyst/Plugins/Utils/Validator/validatorrule.h
Fixes linter warnings in the following plugins:
* CSRFProtection
* Memcached
* MemcachedSessionStore
* LangSelect
* Validator
> Some more linter warning fixes

- tests/testcsrfprotection.cpp
When invalidating a valid token to test for correct behavior with invalid tokens, only digits and letters would be changed but there could also be dashes and underscores. This will now change dashes to underscores and vice versa if they are at the position of the character to invalidate the token.
> CSRFProtection: fix tests

- Cutelyst/Plugins/Authentication/CutelystQt5Authentication.pc.in
- Cutelyst/Plugins/CSRFProtection/CutelystQt5CSRFProtection.pc.in
- Cutelyst/Plugins/Memcached/CutelystQt5Memcached.pc.in
- Cutelyst/Plugins/MemcachedSessionStore/CutelystQt5MemcachedSessionStore.pc.in
- Cutelyst/Plugins/Session/CutelystQt5Session.pc.in
- Cutelyst/Plugins/StaticCompressed/CutelystQt5StaticCompressed.pc.in
- Cutelyst/Plugins/StaticSimple/CutelystQt5StaticSimple.pc.in
- Cutelyst/Plugins/StatusMessage/CutelystQt5StatusMessage.pc.in
- Cutelyst/Plugins/UserAgent/CutelystQt5UserAgent.pc.in
- Cutelyst/Plugins/Utils/LangSelect/CutelystQt5UtilsLangSelect.pc.in
- Cutelyst/Plugins/Utils/Pagination/CutelystQt5UtilsPagination.pc.in
- Cutelyst/Plugins/Utils/Sql/CutelystQt5UtilsSql.pc.in
- Cutelyst/Plugins/Utils/Validator/CutelystQt5UtilsValidator.pc.in
- Cutelyst/Plugins/View/Cutelee/CutelystQt5Cutelee.pc.in
- Cutelyst/Plugins/View/Email/CutelystQt5ViewEmail.pc.in
- Cutelyst/Plugins/View/JSON/CutelystQt5ViewJSON.pc.in
Most of the pkgconfig files still had fixed Qt5 inside.
> Fix pkgconfig files

- Cutelyst/Plugins/Memcached/memcached.cpp
- Cutelyst/Plugins/Memcached/memcached_p.h
* move some stuff into private methods
* fix some linter warnings
> Memcached plugin improvements

- Cutelyst/Plugins/CSRFProtection/csrfprotection_p.h
- Cutelyst/Plugins/Utils/LangSelect/langselect_p.h
- Cutelyst/utils.cpp
- EventLoopEPoll/socknot_p.cpp
- server/protocolwebsocket.cpp
- server/protocolwebsocket.h
- tests/coverageobject.h
* remove some checks for C++20 or newer as we require that anyway as a minimum
* remove some checks for Qt versions not supported anymore
> Cleanup some obsolete stuff

- Cutelyst/Plugins/CSRFProtection/csrfprotection.h
- Cutelyst/Plugins/Memcached/memcached.cpp
- Cutelyst/Plugins/Memcached/memcached.h
- Cutelyst/Plugins/Memcached/memcached_p.h
- Cutelyst/Plugins/Session/CutelystQtSession.5.in
- Cutelyst/Plugins/Session/session.cpp
- Cutelyst/Plugins/Session/session.h
- Cutelyst/Plugins/Session/session_p.h
- Cutelyst/Plugins/Utils/Validator/i18n/plugin_utils_validator.de.ts
- Cutelyst/Plugins/Utils/Validator/i18n/plugin_utils_validator.en.ts
- Cutelyst/Plugins/Utils/Validator/validatorfilesize.cpp
- Cutelyst/Plugins/Utils/Validator/validatorfilesize.h
- Cutelyst/Plugins/Utils/Validator/validatorjson.cpp
- Cutelyst/Plugins/Utils/Validator/validatorjson.h
- Cutelyst/Plugins/Utils/Validator/validatorjson_p.h
- Cutelyst/Plugins/View/Cutelee/csrf.cpp
- Cutelyst/Plugins/View/Cutelee/csrf.h
- Cutelyst/Plugins/View/Cutelee/cuteleeview.h
- Cutelyst/Plugins/View/Cutelee/cutelystcutelee.cpp
- tests/testmemcached.cpp
- tests/testvalidator.cpp
* CSRFProtection plugin: add c_csrf_token_value cutelee tag
* Memcached plugin: convert enum MemcachedReturnType into enum class ReturnType
* Memcached plugin: add overloaded constructor for default config
* Session plugin: add overloaded constructor for default config
* Session plugin: use Utils::durationFromString() to parse expires config enty
* ValidatorFileSize: use QLocale::decimalPoint() in the file size regex for HTML input patterns
* ValidatorJson: add expected type option
> Miscellanious small changes

- Cutelyst/Plugins/Utils/Sql/sql.h
- Cutelyst/Plugins/Utils/Validator/validatorafter.h
- Cutelyst/Plugins/Utils/Validator/validatorbefore.h
This fixes some typos, introduced by ccpcheck fixes.
> Fix some typos

- Cutelyst/Plugins/Utils/Validator/validatoremail.cpp
- Cutelyst/Server/staticmap.cpp
- Cutelyst/dispatcher.cpp
- Cutelyst/dispatchtypechained.cpp
- Cutelyst/dispatchtypepath.cpp
- examples/hello-world/main.cpp
- examples/hello-world/root.cpp
> fix example
