cmd/main.cpp

The QCommandLineOption for server-port and restart needs the two
QStringLiterals for the option names added to the QStringList, not
separated as two function parameters, thus squishing everything to the
right in the terminal

Corrected command line option help

---

Cutelyst/Plugins/Authentication/authentication.cpp

When using multiple authentication realms and therefore
Authentication::userInRealm() instead of Authentication::userExists(),
the authentication check fails in Authentication::userInRealm() because
no realm name hase been set.

Fix authentication with multiple realms.

---

Cutelyst/Plugins/View/Grantlee/grantleeview.cpp
Cutelyst/Plugins/View/Grantlee/grantleeview.h
Cutelyst/Plugins/View/Grantlee/grantleeview_p.h

Without a QTranslator set for the selected locale, Grantlee::QtLocalizer
will use QCoreApplication::translate() to translate strings. This does
not work together with the current implementation where only a
Grantlee::QtLocalizer with a QLocale is set.
GrantleeView::addTranslator() will add a new QTranslator object for a
specified locale to an internal map of QTranslator object pointers. In
GrantleeView::render() it will set the appropriate QTranslator to the
Grantlee::QtLocalizert object.

GrantleeView: implement adding of QTranslator

---

Cutelyst/Plugins/View/Grantlee/grantleeview.cpp
Cutelyst/Plugins/View/Grantlee/grantleeview.h
Cutelyst/Plugins/View/Grantlee/grantleeview_p.h
Cutelyst/application.cpp
Cutelyst/application.h
Cutelyst/application_p.h
Cutelyst/context.cpp
Cutelyst/context.h

This implements basic translation functionality into the Context and Application. QTranslator objects can be added to the main Application object (best in init() function) and are used from there by the Context to translate strings. Other stuff like numbers can be localized directly by Context::locale().
The Context now has a translate() function that takes the translation context, source string, optional disambiguation and plural. This will be used together with the current Context::locale() to get a translation from Application::translate() that iterates over all installed QTranslator objects for the given locale to return the translated string.
I used _translate()_ for the function name instead of something like ctr() because it is used like QTranslator::translate() not like …

Context translation support

---

Cutelyst/Plugins/Session/sessionstorememcached.cpp

Qt 5.8 deprecated some methods of QDateTime, especially toTime_t(). Qt
docus say deprecated at one place and obsolete at another place. At
least openSUSE packages seems not to export the deprecated method
toTime_t() anymore with Qt 5.8. So this little switch helps to build the
SessionStoreMemcached on Qt 5.8.

Fix build SessionStoreMemcached on Qt 5.8.

---

Cutelyst/Plugins/Session/session.cpp

Session plugin tries to get its configuration from the Application
instance, that only contains configuration values from the [Cutelyst]
section. Engine provides access to all other settings sections defined
in the ini file. So I changed the Session plugin setup to load the
appropriate section.

Fix SessionPlugin settings setup.

---

CMakeLists.txt
cmake/modules/Doxyfile.in

Some automatic package build services, like OBS, compare built packages
to determine if something has changed. If nothing has changed, the built
packages are not pushed to the repositories. Disabling the timestamp in
the doxygen generated footer helps to prevent pushing automatic rebuilds
to the repos where only the timestamp in the footer changed.

Add cmake option to disable Doxygen footer timestamp.

---

CMakeLists.txt
cmake/modules/Doxyfile.in

openSUSE and Fedora are using a different name for the
qhelpfilegenerator, so it is easier for packagers if one can change it.
Additionally I enabled the generation of a cutelyst doxygen tag file
that can be used in 3rd party api documentation.

Add cmake option to set qhelpgenerator path, enable tag file.

---

Cutelyst/CMakeLists.txt

Fix for https://github.com/cutelyst/cutelyst/issues/51
The output directories for WIN32 builds are specified already here https://github.com/cutelyst/cutelyst/blob/master/CMakeLists.txt#L45.

Install dll's in the same folder whith runtime when building with MSVC

---

Cutelyst/Plugins/Memcached/memcached.cpp
tests/testmemcached.cpp

I used QFlags::testFlag() that was introduced in Qt 5.7 so that it breaks compatibility to Qt 5.6. Beside that there is now support for default compression settings and compression is enabled for the unit tests.

Memcached plugin Qt 5.6 compatibility fix

---

Cutelyst/Plugins/StaticCompressed/staticcompressed.cpp

Not sure how that could go through the compiler. Found it when building packages...

StaticCompressed plugin: fix passing non-trivially-copyable type

---

Cutelyst/Plugins/Utils/Validator/validatorresult.cpp
Cutelyst/Plugins/Utils/Validator/validatorresult.h

This adds some small convenience functions to ValidatorResult for easier handling with JSON APIs. First one is ValidatorResult::errorsJsonObject() that returns the input field names with their errors as JSON object. The other one is ValidatorResult::failedFields() that simply returns a list of all field names that have validation errors.

ValidatorResult: add some convenience functions

---

Cutelyst/Plugins/Memcached/memcached.cpp

When using a unix socket to connect to the Memcached server, the
configuration string for the socket missed quotation marks. Other than
connectiong to a server using TCP or UDP, the string for the socket
connection needs quotation marks to handle path names correctly.

Fix Memcached plugin when using unix socket to connect to server

---

Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
Cutelyst/Plugins/CSRFProtection/csrfprotection.h

I added a note to the documentation how to handle redirects with CSRF
protection. Additionally I added a new static method to check the result
of the CSRF protection in contoller methods.

CSRFProtection plugin: improve docs and add method to check result

---

Cutelyst/Plugins/Memcached/memcached.cpp
Cutelyst/Plugins/Memcached/memcached.h
tests/testmemcached.cpp

After finding the issue with the socket connections to memcached servers, I improved the unit tests for the plugin by making it possible to test against multiple and/or different memcached servers, by optionally read the servers used for testing from the environment variable CUTELYST_MEMCACHED_TEST_SERVERS.

Improve unit tests for memcached plugin

---

Cutelyst/Plugins/Memcached/memcached.cpp
Cutelyst/Plugins/Memcached/memcached.h
Cutelyst/Plugins/Memcached/memcached_p.h

libmemcached provides the preprocessor definition
LIBMEMCACHED_WITH_SASL_SUPPORT. Use this to enable or disable the
support for SASL authentication in the libmemcached based Cutelyst
Memcached plugin.

Memcached plugin: add preprocessor switch to enable/disable SASL support

---

CMakeLists.txt
Cutelyst/Plugins/CSRFProtection/CMakeLists.txt
Cutelyst/Plugins/CSRFProtection/CutelystQt5CSRFProtection.5.in
Cutelyst/Plugins/Memcached/CMakeLists.txt
Cutelyst/Plugins/Memcached/CutelystQt5Memcached.5.in
Cutelyst/Plugins/MemcachedSessionStore/CMakeLists.txt
Cutelyst/Plugins/MemcachedSessionStore/CutelystQt5MemcachedSessionStore.5.in
Cutelyst/Plugins/Session/CMakeLists.txt
Cutelyst/Plugins/Session/CutelystQt5Session.5.in
Cutelyst/Plugins/Session/session.h

I wrote small man pages for some of my plugins describing the various configuration file options read by this plugins. In particular they cover the following plugins:
* Memcached
* MemcachedSessionStore
* CSRFProtection
They will be installed in the man page section number 5 (File formats and configuration files).

Add configuration man pages to some plugins

---

Cutelyst/Plugins/Utils/Validator/validator.h
Cutelyst/Plugins/View/Grantlee/CMakeLists.txt

Public headers for the Grantlee view plugin were installed into the JSON view headers directory. Also fixing wrong component name in validator plugin documentation.

Fix wrong install location for Grantlee view headers

---

Cutelyst/Plugins/Utils/Validator/validatorfilesize.cpp
Cutelyst/Plugins/Utils/Validator/validatorfilesize.h

Adds a small static method ValidatorFileSize::inputPattern() that
returns a string containing usable as pattern on an input text field
that matches the validator according to the language direction.

Validator file size: add method to get matching input field pattern

---

Cutelyst/Plugins/Utils/Validator/CMakeLists.txt
Cutelyst/Plugins/Utils/Validator/Validators
Cutelyst/Plugins/Utils/Validator/validatorrequiredifstash.cpp
Cutelyst/Plugins/Utils/Validator/validatorrequiredifstash.h
Cutelyst/Plugins/Utils/Validator/validatorrequiredifstash_p.h
Cutelyst/Plugins/Utils/Validator/validatorrequiredunlessstash.cpp
Cutelyst/Plugins/Utils/Validator/validatorrequiredunlessstash.h
Cutelyst/Plugins/Utils/Validator/validatorrequiredunlessstash_p.h
tests/testvalidator.cpp

Till now there were only requirement validators that compared against other input fields. Now I added two that work like the ones that use the input fields but instead using the current stash.

Validator plugin: add two required validators that use the stash

---

Cutelyst/Plugins/Utils/Validator/CMakeLists.txt
Cutelyst/Plugins/Utils/Validator/Validators
Cutelyst/Plugins/Utils/Validator/validatordomain.cpp
Cutelyst/Plugins/Utils/Validator/validatordomain.h
Cutelyst/Plugins/Utils/Validator/validatordomain_p.h
tests/testvalidator.cpp

This validator will check if an input field contains a domain name that
is valid according to RFC 1035 and can optionally also check it's
existence in the domain name system through a host name lookup.

Validator plugin: add new ValidatorDomain to check domain names

---

.travis.yml
CMakeLists.txt
Cutelyst/Plugins/Utils/Validator/CMakeLists.txt
Cutelyst/Plugins/Utils/Validator/validator.h
Cutelyst/Plugins/Utils/Validator/validatorpwquality.cpp
Cutelyst/Plugins/Utils/Validator/validatorpwquality.h
Cutelyst/Plugins/Utils/Validator/validatorpwquality_p.h
appveyor.yml
tests/CMakeLists.txt
tests/testvalidator.cpp

This new validator uses libpwquality to generate a password quality
score that will be compared against a threshold. If the score is below
the threshold, the validation fails. As this relies on an external
library it is not build by default. Use -DPLUGIN_VALIDATOR_PWQUALITY:BOOL=ON
or -DBUILD_ALL:BOOL=ON to enable its build.

Validator plugin: new ValidatorPwQuality

---

Cutelyst/Plugins/Utils/Validator/validatorpwquality.cpp
Cutelyst/Plugins/Utils/Validator/validatorpwquality.h
tests/testvalidator.cpp

Do not fail the validation if one or more options are not available in the used version of libpwquality. Instead use the defaults and print a warning to the logging category.

ValidatorPwQuality: improve application of options

---

tests/testvalidator.cpp

As every password to test makes it harder to predict the outcome when
compared with different versions of libpwquality, there will be now only
one real test vor invalidity.

ValidatorPwQuality unit tests: use less invalid password tests

---

tests/testvalidator.cpp

I am not sure where the problem is. Running the tests on my local
machine, everythings works as expected. Running the same tests in Travis
CI or when building packages in the openSUSE Build Service, it seems as
if the password score is not computed anymore but diced. At first I
thought it would be related to different versions of libpwquality - and
it still seems to be one part of the problem. But how can a password
"1234" can get a score higher than 50 on any library version??? And than
in the next run, a really complicated and long one gets a score below
50. Maybe my implementation is shit, but if I compare it against the one
of the libpwquality command line utility pwscore, it is not really
different. Will try it again tomorrow, hopefully without spamming the
pull requests...

ValidatorPwQuality: disable unit tests for now

---

Cutelyst/Plugins/Utils/Validator/validatorrule.cpp

The optional errorData that can be use when generating validation error
messages was not forwareded to the generic functions

Validator plugin: fix erroData not forwarded to generic methods

---

Cutelyst/Plugins/Utils/Validator/validatorpwquality.cpp
Cutelyst/Plugins/Utils/Validator/validatorpwquality.h

If the options contain an emtpy QVariantMap with options or an empty
QString that should point to a pwquality settings file, read the options
from the default settings file.

ValidatorPwQuality: load default config file if config is empty

---

CMakeLists.txt
Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
Cutelyst/Plugins/Memcached/memcached.cpp
Cutelyst/Plugins/Utils/Validator/validator.cpp
Cutelyst/Plugins/Utils/Validator/validator.h
Cutelyst/Plugins/View/Grantlee/grantleeview.cpp
Cutelyst/application.cpp
Cutelyst/application.h
Messages.sh
cmd/main.cpp
config.h.in
i18n/CMakeLists.txt
i18n/cutelystcmd.ts
i18n/cutelystcore.ts
i18n/cutelystwsgi.ts
i18n/plugin_csrfprotection.ts
i18n/plugin_memcached.ts
i18n/plugin_utils_validator.ts
i18n/plugin_view_grantlee.ts
wsgi/main.cpp

This changes will add support for translation extraction and translation loading.
Extraction is done in a shell script (Messages.sh) that will extract translations from different parts into different translation source files in the i18n directory. My current proposal for the parts:
* i18n/cutelystcmd.ts contains all translations from the cmd subdirectory
* i18n/cutelystwsgi.ts contains all translation from the wsgi subdirectory
* i18n/cutelystcore.ts contains all translations from the Cutelyst directory **withouth** the content from the subdirectories
* i18n/plugin_memcached.ts contains all translations from the Cutelyst/Plugins/Memcached subdirectory
* i18n/plugin_csrfprotection.ts contains all translations from the Cutelyst/Plugins/CSRFProtection subdirectory
* …

Translation extraction and loading

---

Cutelyst/Plugins/Utils/Validator/validatoremail.cpp
Cutelyst/Plugins/Utils/Validator/validatoremail.h
Cutelyst/Plugins/Utils/Validator/validatoremail_p.h
tests/testvalidator.cpp

Adds support for Email Address Internationalization (EAI) as defined in RFC 6531 (SMTPUTF8 extension).

ValidatorEmail: add support for UTF8 local part and IDNs

---

wsgi/wsgi.cpp

Trivial fix for an error only happens on GCC.

wsgi: fix ambigious overload

---

wsgi/protocolfastcgi.cpp

At least this fixed the FastCGI issue for me, I am not sure if I
implemented it the correct way as I was not diving deep into FCGI
protocol.
GDB output before this fix:
Thread 2.2 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee1d0700 (LWP 7141)]
CWSGI::ProtoRequestFastCGI::doWrite (this=this@entry=0x7fffe800cd40,
data=0x7fffe8010538 "Status: 302\r\nContent-Type: text/html; charset=utf-8\r\nServer: cutelyst/2.0.0\r\nX-Robots-Tag: none\r\nReferrer-Policy: no-referrer, strict-origin-when-cross-origin\r\nContent-Security-Policy: default-src 'no"..., len=560) at /usr/src/debug/cutelyst-1.99.60git.1520736217.6be7b34/wsgi/protocolfastcgi.cpp:562
562                 fr.req1 = sid[1];

Fix FastCGI protocol segfault

---

Cutelyst/Plugins/Authentication/htpasswd.cpp

Previously colons were not replaced.

Fix StoreHtpasswd::addUser if file doesn't exist

---

Cutelyst/Plugins/Utils/Sql/sql.cpp

The changes ensure that the querying of the record will be done only once.

Changes in Sql utils functions in sql.cpp. 

---

CMakeLists.txt

Other than this it seems Cutelyst runs okay on Haiku.
https://www.haiku-os.org/
I've tested only a hello world example:
https://ibb.co/S64YCX4
Can't find a way to disable IPv6 so I found the appropriate address from here:
https://stackoverflow.com/a/46711717

Haiku doesn't have sys/epoll.h so disable EventLoopEPoll

---

wsgi/staticmap.cpp

I had an identical static map in the ini-file and on the command line. That resulted in file descriptor leakages.
This pull request should fix this problem.

fix file descriptor leakage in static map (if misused)

---

wsgi/protocolhttp.cpp

In https mode, when redirect, Request::uri doesn't return a https scheme url. And the scheme is controlled by d->engineRequest->isSecure. Howerver, ProtoRequestHttp doesn't set isSecure to match Socket's. The change sets isSecure when ProtoRequestHttp is constructed. I'm new to this project, don't know if there is any side-effect.

Set isSecure on ProtoRequestHttp CTor

---

Cutelyst/view.cpp
Cutelyst/view.h

There is StaticCompressed plugin that does good job for css and js files. But the generated view output is in plain text. This commit allows view output to be compressed if it's larger than 1KB(hmm, I don't know how many is best, let me know if you have suggestions).

Deflate view output if it's larger than minimal size  and accepted by client

---

wsgi/hpack.cpp
wsgi/protocolhttp2.cpp
wsgi/tcpserverbalancer.cpp

- Let sendGoAway and sendRstStream return error, so that socket can then close connection in ProtocolHttp2::parse(). 
- Handle more Stream state exceptions. 
- In case of small window size, H2Stream::doWrite may write partial data, and need to add offset to data. If I misunderstand it, please correct me.

Fix ProtoRequestHttp2, now passes h2spec tests

---

Cutelyst/Plugins/View/Grantlee/grantleeview.cpp

When setting up grantlee plugin paths do this also for the paths of the env variable CUTELYST_PLUGINS_DIR
This makes it possible to use grantlee plugin when the hard coded plugin path doesn't exists on the target system and CUTELYST_PLUGINS_DIR env var is properly setup

Grantlee plugin support CUTELYST_PLUGINS_DIR env var 

---

Cutelyst/Plugins/Utils/Validator/validatorrule_p.h

There was a wrong conversion to short instead of int in one of the validator helper function.s

Validator plugin: fix wrong type conversion for integer

---

Cutelyst/Plugins/Memcached/memcached.cpp

When calling Cutelyst::Memcached::removeByKey(), the correct return type
was not set.

Fix missing return type at Memcached::removeByKey()

---

Cutelyst/Plugins/StaticCompressed/staticcompressed.cpp

gzip_container.h isn't a standard header for zopfli. Changing it to use the main header.

Use main zopfli header

---

wsgi/wsgi.cpp

When multiple config files should be loaded an endless loop occures while merging the config data

Fixed endless loop when more then one config files should be loaded

---

CMakeLists.txt

Since usage of GNUInstallDirs, the path to the translations configured in config.h does not contain the prefix anymore. We should use `CMAKE_INSTALL_FULL_DATADIR` to set the `I18NDIR` path.

Fix loading of included translations

---

CMakeLists.txt

CMake’s VERSION_GREATER_EQUAL was introduced in CMake 3.7. To still support older versions of CMake, especially on long living distributions, use VERSION_GREATER.

Use CMake VERSION_GREATER instead of VERSION_GREATER_EQUAL

---

Cutelyst/Plugins/View/Cutelee/cuteleeview.cpp
Messages.sh
i18n/CMakeLists.txt
i18n/plugin_view_cutelee.de.ts
i18n/plugin_view_cutelee.en.ts

Use Cutelee::Engine::insertDefaultLibrary() to insert the Cutelyst specific Cutelee tags into every template by default to get a behavior like on our GrantleeView.
Enable translations for CuteleeView.

CuteleeView: use insertDefaultLibrary() for internal Cutelyst tags and add translations

---

Cutelyst/Plugins/Session/CutelystQt5Session.5.in
Cutelyst/Plugins/Session/session.cpp
Cutelyst/Plugins/Session/session.h

There are some options for the plugin like `cookieSecure` and `cookieHttpOnly` that are not configurable from the configuration file because no entries for them are loaded from the config file. This adds the loading of the two config file entries `cookie_http_only` and `cookie_secure` to the setup() method.
This will also update the man pages and API docs for this config entries.

[Session Plugin] load config file options

---

Cutelyst/CMakeLists.txt
Cutelyst/enginerequest.h

I had a need to test an endpoint. This is a quick fix to be able to unit tests endpoints until a full public API like TestEngine (see #176) is available.

make header enginerequest.h available for external unit tests

---

wsgi/unixfork.h

This resolves a warning from clang:
```
In file included from /usr/home/adridg/src/git/cutelyst/wsgi/unixfork.cpp:18:
/usr/home/adridg/src/git/cutelyst/wsgi/unixfork.h:27:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
^
Worker
/usr/home/adridg/src/git/cutelyst/wsgi/unixfork.h:28:17: note: type is not C-compatible due to this default member initializer
bool null = true;
^~~~
/usr/home/adridg/src/git/cutelyst/wsgi/unixfork.h:32:3: note: type is given name 'Worker' for linkage purposes by this typedef declaration
} Worker;
^
```
It's because of the C-style typedef (that looks like it is a leftover from the original WSGI code).

Replace C-style typedef with regular C++

---

CMakeLists.txt

This is a patch that I've been carrying in packaging for some time: FreeBSD is UNIX and not APPLE OR HAIKU, so it is detected as Linux. It isn't, though, and the available epoll shim (FreeBSD does that a lot: once Linux has created  some arbitrary API and everyone is using it, build a shim for that API to the services available in the BSD world) doesn't have the whole API used.
So futz around a bit, but conclude: FreeBSD isn't Linux. Some time in future that commented-out line could be added if the shim is extended enough.

Handle FreeBSD nicely

---

Cutelyst/ActionChain
Cutelyst/CMakeLists.txt

The class is already documented as a public class, and is needed to
implement chained dispatchers.

core: Make the ActionChain class public

---

qtcreator/cutelyst/projects/CMakeLists.txt
server/main.cpp
server/server.cpp
server/server.h
server/server_p.h
server/tcpserverbalancer.cpp
server/unixfork.cpp
server/unixfork.h

Most of qFatals and exit()s has been replaced by handlers which emits errorOccured signal. This behavior will prevent qApplication fail on Server errors.

Revisions in Server to avoid application fail on Server errors

---

CMakeLists.txt

TL;DR As the title.
Details:
When I use this library with Qt6,
I add the following lines in my CMakeLists.txt, CMake complaint that cannot find the library(cutelyst).
```
find_package(QT NAMES Qt6 Qt5 COMPONENTS Core Network REQUIRED)
find_package(Cutelyst3Qt${QT_VERSION_MAJOR} REQUIRED)
```
Even I set "Cutelyst3Qt6_DIR" to my environment variable, CMake still complaint about that.

make sure cmake can find library with qt6

---

server/CMakeLists.txt

Don't override `CMAKE_EXE_LINKER_FLAGS` as this could break the build if
`CMAKE_EXE_LINKER_FLAGS` is already set by the user (for example to pass
`-latomic`)
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

server/CMakeLists.txt: don't override CMAKE_EXE_LINKER_FLAGS

---

Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
Cutelyst/Plugins/CSRFProtection/csrfprotection.h

At first I thought it was a bug in the plugin, hence the branch name csrffix. But in the end it was only necessary to clarify the documentation.
The other changes are more of cosmetic nature.

Some minor improvements for the CSRFProtection plugin

---

Cutelyst/Plugins/View/Cutelee/cuteleeview.cpp
Cutelyst/Plugins/View/Cutelee/cuteleeview_p.h

When setting CuteleeView::setCache() to either `true` or `false` (it
does not matter), a new Cutelle::Engine object was created and the old
one was deleted. Some settings for the engine object were reapplied to
the new object, but not all: plugin paths and inserting the
CutelystCutelee as default library was not reapplied so it was missing
when setting setCache() in any way.
This puts some initialization steps in a private mehtod and calls it in
the constructor as well as when changing caching.

CuteleeView: fix initializing Cutelee::Engine after setting cache (closes #330)

---

CMakeLists.txt

When overwriting the complete variable, some Qt6 CMake modules like FindWrapOpenGL.cmake do not work as expected.

Append our module path to CMAKE_MODULE_PATH

---

tests/testcsrfprotection.cpp

Do not use auto for the variable to store QChar& when using operator[] on QString as it will return const QChar instead when a reference is needed. For the const QChar it is naturally not possible to change the value of the char in the string as it would be needed to generate invalid tokens.

CSRFProtection plugin: fix tests

---

tests/testcsrfprotection.cpp

I should have checked if the previous fix also works on Qt5 - it did not. Overloading of the QString::operator[] changed from Qt5 to Qt6, as Qt5 returns a QCharRef instead of QChar&.

CSRFProtection plugin: fix tests on Qt5

---

CMakeLists.txt
EventLoopEPoll/CMakeLists.txt
server/CMakeLists.txt

This upstreams and simplifies some build-time patches on FreeBSD.
Note that the server code calls `epoll->reinstall()` so epoll is effectively mandatory now. To reflect that I've updated the FreeBSD packaging, but we can make things simpler by upstreaming it.

Simplify build on FreeBSD

---

CMakeLists.txt

Doxygen changed the default font name for dot images to Helvetia that might not be available. In the past we used FreeSans for the dot command. This sets FreeSans as font for dot with old and new configuration values.

Set doxygen dot font name and font size

---

Cutelyst/Plugins/Memcached/memcached.h
tests/testmemcached.cpp

Automatically start a memcached server if no previously started server has been set via `CUTELYST_MEMCACHED_TEST_SERVERS` environment variable. The server will be terminated after the tests finished.

Memcached Plugin tests: start memcached server for testing

---

tests/testvalidator.cpp

This fixes the percent encoding of datetime values that contain a timezone offset. The parsing in Qt6 is more strict and fails if the + sign is missing.

Validator Plugin tests: fix some more datetime input values

---

Cutelyst/CMakeLists.txt
Cutelyst/Cookie
Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
Cutelyst/Plugins/CSRFProtection/csrfprotection.h
Cutelyst/Plugins/CSRFProtection/csrfprotection_p.h
Cutelyst/Plugins/Session/session.cpp
Cutelyst/Plugins/Session/session.h
Cutelyst/Plugins/Session/session_p.h
Cutelyst/Plugins/Utils/LangSelect/langselect.cpp
Cutelyst/cookie.cpp
Cutelyst/cookie.h
Cutelyst/cookie_p.h
Cutelyst/enginerequest.cpp
Cutelyst/response.cpp
Cutelyst/response.h
Cutelyst/response_p.h
tests/CMakeLists.txt
tests/testauthentication.cpp
tests/testcookie.cpp

This adds the SameSite attribute to some cookies set by plugins like Session, CSRFProtection and LangSelect if compiled against Qt 6.1+. For the Session and CSRFProtection plugins the attribute is configurable and set to Strict by default. For the LangSelect plugin the attribute is set to Lax.
I am not sure if Strict might be to hard as default. Maybe Lax as default would be better for backwards compatibility as browsers should use Lax for Cookies without SameSite attribute. What do you think @dantti ?

SameSite attribute for cookies

---

Cutelyst/Plugins/Utils/Validator/validatorresult.cpp

ValidatorResult::errors(const QString &field) had no implementation.

Validator plugin: fix missing implementation for ValidatorResult::errors

---

Cutelyst/action.cpp
Cutelyst/action_p.h

Qt 6.5 introduced a new variadic version of QMetaMethod::invoke() that does not work with our current implementation. This adds a fast fix to use the new variadic version of QMetaMethod::invoke() on Qt 6.5+ but there might be better / more elegant approaches to fix the issue.

Use variadic version of QMetaMethod::invoke() on Qt 6.5 (closes #391)

---

Cutelyst/action.cpp
Cutelyst/action_p.h
Cutelyst/context.h

This adds Context::qtTrId() method that works similar to Qt’s global qtTrId() function and supports ID based translations without specifying a context like with Context::translate().

Add Context::qtTrId() method to support ID based translations

---

Cutelyst/Plugins/View/Grantlee/grantleeview_p.h
Cutelyst/action.cpp
Cutelyst/action_p.h

GrantleeViewPrivate has a virtual default destructor that is marked as override but that does not override anything because the base classes do not have a destructor specified.

GrantleeView: fix incorrect override

---

Cutelyst/headers.cpp
tests/testheaders.cpp

The compare in the lambda for the QVector::removeIf missed the 0 to compare against. I also added a test for Headers::removeHeader(). This also fixes the issues with the tests for the LangSelect and CSRFProtection plugins that relied on Headers::removeHeader().

Fix Headers::removeHeader() and add tests

---

Cutelyst/multipartformdataparser.cpp

On aarch64 platform GCC throws an error about uninitialized startOffest variable. This initializes the variable with 0.

MultiPartFormDataParser: fix uninitialized

---

Cutelyst/Plugins/CSRFProtection/csrfprotection.cpp
Cutelyst/Plugins/CSRFProtection/csrfprotection.h
Cutelyst/Plugins/CSRFProtection/csrfprotection_p.h

Add a constructor that takes a QVariantMap to override the default values for config file entries.

CSRFProtection plugin: add constructor with default config

---

CMakeLists.txt
Cutelyst/Plugins/StaticCompressed/staticcompressed.cpp
Cutelyst/Plugins/StaticCompressed/staticcompressed.h
Cutelyst/Plugins/StaticCompressed/staticcompressed_p.h

Add a constructor that takes a QVariantMap to override the default values for config file entries.

StaticCompressed plugin: add constructor with deafult config

---

Cutelyst/application.cpp
Cutelyst/application.h
Cutelyst/application_p.h
Cutelyst/context.cpp
Cutelyst/context.h
Cutelyst/context_p.h
Cutelyst/testengine.cpp
cmd/CMakeLists.txt

The default locale of QLocale’s default constructor is not comparable to the QLocale objects constructed from strings or enums. The internal default will now be US english. The default locale set in application will now be used to populate the locale setting of the context.

Application: add default locale setting

---

server/server.cpp
server/server_p.h
tests/testserver.cpp

* This fixes the loading of included config files pointed to by `ini` or `json` config key in `server` section.
* Adds more tests.
* Cleanup obsolete outcommented server section name detection from config file name

Server::loadConfig(): fix loading of included config files, cleanup, add more tests

---

Cutelyst/Plugins/StaticCompressed/CMakeLists.txt
Cutelyst/Plugins/StaticCompressed/staticcompressed.cpp
Cutelyst/Plugins/StaticCompressed/staticcompressed.h
Cutelyst/Plugins/StaticCompressed/staticcompressed_p.h
tests/teststaticcompressed.cpp

This adds support for Zstandard compression if enabled via CMake `-DPLUGIN_STATICCOMPRESSED_ZSTD:BOOL=ON`. For this the header and development files of libzstd >= 1.4.0 are required.
Also improves and fixes the internal _gzip_ and _deflate_ compression created by qCompress().
Adds a new configuration file option `compression_format_order` to select the order of the available compression formats.

StaticCompressed plugin: add support for Zstandard compression and other improvements

---

Cutelyst/Plugins/Utils/Validator/validatorfilesize.cpp

This reverts a prvious change in ValidatorFileSize that used std::lround. As the value is stored as unsigned long long init, even std::llround would not be sufficient and might result in an overflow. Current approach might not be the best but it works.

Fix ValidatorFileSize

---

Cutelyst/CoroContext.h

This adds variadic template constructors to the CoroContext::promise_type that takes the coroutine parameters to give the promise type access to them. The constructor connects the QObject::destroyed signal of the context as before the yield_value methods did. So there is no need anymore to call `co_yield c` in the coroutine context method.

Remove need for co_yield context in context coroutine method
